###
GET http://localhost:3005/videos

###
GET http://localhost:3005/videos/3452435

###
GET http://localhost:3005/videos/65745674

###
DELETE http://localhost:3005/testing/all-data

###
DELETE http://localhost:3005/videos/3452435

###
DELETE http://localhost:3005/videos/65745674

###
POST http://localhost:3005/videos
Content-Type: application/json

{
  "title": "What a title",
  "author": "Elon Musk",
  "availableResolutions": ["P144", "P360", "P1080"]
}

###
POST http://localhost:3005/videos
Content-Type: application/json

{
  "title": "What a title",
  "author": "Elon Musk",
  "availableResolutions": ["P140", "P360", "P1080"]
}

###
POST http://localhost:3005/videos
Content-Type: application/json

{
  "availableResolutions": ["P144", "P360", "P1080"]
}
